# Generated by Django 4.1.4 on 2022-12-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_in_cart',
            new_name='number_of_items_in_cart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
